# Generated by Django 5.1.15 on 2026-09-04 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField()),
                ("description", models.CharField(max_length=200)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Emoji, used when there is no image",
                        max_length=8,
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="badges/")),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("scan_count", "Scan N markers"),
                            ("discover_animal", "Discover specific animal(s)"),
                            (
                                "discover_count",
                                "Discover N animals (optionally with a tag)",
                            ),
                            ("exhibit_count", "Scan in N different exhibits"),
                            ("challenge_type_count", "Complete N challenges of a type"),
                            ("quest_complete", "Complete a quest"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "rule_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='e.g. {"count": 5, "tag": "africa"} or {"quest_slug": "savanna-safari"}',
                    ),
                ),
                ("xp_reward", models.PositiveIntegerField(default=0)),
                (
                    "is_secret",
                    models.BooleanField(
                        default=False, help_text="Hidden in the badge case until earned"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "zoo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.zoo",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("zoo", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Exhibit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField()),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="exhibits/")),
                (
                    "map_x",
                    models.DecimalField(
                        decimal_places=2,
                        default=50,
                        help_text="Pin position, % from the left of the map image",
                        max_digits=5,
                    ),
                ),
                (
                    "map_y",
                    models.DecimalField(
                        decimal_places=2,
                        default=50,
                        help_text="Pin position, % from the top of the map image",
                        max_digits=5,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "zoo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.zoo",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "unique_together": {("zoo", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="What a kid calls it: Giraffe", max_length=120
                    ),
                ),
                ("slug", models.SlugField()),
                (
                    "species",
                    models.CharField(
                        blank=True, help_text="Reticulated giraffe", max_length=160
                    ),
                ),
                ("scientific_name", models.CharField(blank=True, max_length=160)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="animals/")),
                (
                    "emoji",
                    models.CharField(
                        blank=True,
                        help_text="Fallback icon when there is no image",
                        max_length=8,
                    ),
                ),
                (
                    "fun_facts",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of short facts, one per line in the admin",
                    ),
                ),
                (
                    "conservation_status",
                    models.CharField(
                        choices=[
                            ("LC", "Least Concern"),
                            ("NT", "Near Threatened"),
                            ("VU", "Vulnerable"),
                            ("EN", "Endangered"),
                            ("CR", "Critically Endangered"),
                            ("EW", "Extinct in the Wild"),
                            ("EX", "Extinct"),
                            ("DD", "Data Deficient"),
                        ],
                        default="DD",
                        max_length=2,
                    ),
                ),
                (
                    "conservation_info",
                    models.TextField(
                        blank=True, help_text="Written for a nine-year-old"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lowercase tags badges and clues key off: africa, reptile, stripes",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "zoo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.zoo",
                    ),
                ),
                (
                    "exhibit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="animals",
                        to="content.exhibit",
                    ),
                ),
            ],
            options={
                "ordering": ["exhibit__sort_order", "name"],
                "unique_together": {("zoo", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Marker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Printed on the sign. Generated if left blank.",
                        max_length=40,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="For staff: 'Giraffe viewing rail'", max_length=120
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="markers",
                        to="content.animal",
                    ),
                ),
                (
                    "exhibit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="markers",
                        to="content.exhibit",
                    ),
                ),
                (
                    "zoo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.zoo",
                    ),
                ),
            ],
            options={
                "ordering": ["exhibit__sort_order", "code"],
                "unique_together": {("zoo", "code")},
            },
        ),
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("slug", models.SlugField()),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("animal_hunt", "Animal Hunt"),
                            ("scavenger", "Scavenger Hunt"),
                            ("who_am_i", "Who Am I?"),
                            ("observation", "Observation"),
                            ("photo", "Photo"),
                            ("conservation", "Conservation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="easy",
                        max_length=10,
                    ),
                ),
                (
                    "xp_reward",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Leave 0 to use the zoo default for this difficulty",
                    ),
                ),
                ("prompt", models.TextField(help_text="What the family reads")),
                ("hint", models.TextField(blank=True)),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Shown after completion: the learning beat",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Type-specific: options, correct, timer_seconds",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "animal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="challenges",
                        to="content.animal",
                    ),
                ),
                (
                    "zoo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.zoo",
                    ),
                ),
                (
                    "exhibit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="challenges",
                        to="content.exhibit",
                    ),
                ),
                (
                    "accept_markers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Scanning any of these completes the challenge",
                        related_name="challenges",
                        to="content.marker",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
                "unique_together": {("zoo", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField()),
                ("description", models.TextField(blank=True)),
                ("cover_image", models.ImageField(blank=True, upload_to="quests/")),
                (
                    "xp_reward",
                    models.PositiveIntegerField(
                        default=0, help_text="Leave 0 to use the zoo default"
                    ),
                ),
                (
                    "estimated_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="For seasonal quests. Blank = always",
                        null=True,
                    ),
                ),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "badge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quests",
                        to="content.badge",
                    ),
                ),
                (
                    "zoo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.zoo",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="QuestChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "is_final",
                    models.BooleanField(
                        default=False,
                        help_text="The last mission; completing it completes the quest",
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quest_steps",
                        to="content.challenge",
                    ),
                ),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="content.quest",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("quest", "challenge"), ("quest", "order")},
            },
        ),
        migrations.AddField(
            model_name="quest",
            name="challenges",
            field=models.ManyToManyField(
                related_name="quests",
                through="content.QuestChallenge",
                to="content.challenge",
            ),
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=80)),
                ("xp_required", models.PositiveIntegerField()),
                (
                    "zoo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.zoo",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "unique_together": {("zoo", "number")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="quest",
            unique_together={("zoo", "slug")},
        ),
    ]
