# Generated by Django 5.1.15 on 2026-09-04 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Zoo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "slug",
                    models.SlugField(help_text="Used in URLs: /z/<slug>", unique=True),
                ),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("logo", models.ImageField(blank=True, upload_to="zoos/logos/")),
                (
                    "map_image",
                    models.ImageField(
                        blank=True,
                        help_text="Static map image that exhibit pins are placed on.",
                        upload_to="zoos/maps/",
                    ),
                ),
                ("primary_color", models.CharField(default="#2F6B4F", max_length=7)),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="discovery_xp, quest_complete_xp, xp_by_difficulty, repeat_scan_cooldown_minutes",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StaffMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("editor", "Editor"),
                            ("viewer", "Viewer"),
                        ],
                        default="editor",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zoo_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zoo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tenants.zoo",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "zoo")},
            },
        ),
    ]
